mysql_credentials:
  host: localhost
  port: 3306
  username: root
  password: pa55w0rd
  database: huskrtp
  params: '?autoReconnect=true&useSSL=false'
  player_table_name: huskrtp_players
redis_credentials:
  host: localhost
  port: 6379
  password:
average_player_count_days: 7
update_plan_data_hours: 1
this_server_id: server1
use_plan: false
last_rtp_on_cooldown: true
default_rtp_group: group1
groups:
  group1:
    table_name: huskrtp_group_1
    cooldown_minutes: 6
    servers_worlds:
      server1:
        - world
        - worldcustomgen
      server2:
        - world
        - worldgen2
  group2:
    table_name: huskrtp_group_2
    cooldown_minutes: 3
    servers_worlds:
      server3:
        - worldcustomgen