name: HuskBungeeRTP
version: ${project.version}
main: me.william278.huskbungeertp.HuskBungeeRTP
api-version: 1.17
author: William278
website: ${project.url}
description: ${project.description}
depend:
  - HuskHomes
softdepend:
  - JakesRTP
  - Plan

commands:
  rtp:
    usage: /rtp [player] [group] [biome]
    description: Randomly teleport a player
    permission: huskrtp.command.rtp
  huskbungeertp:
    usage: /huskbungeertp <about/groups/plan/reload>
    description: View and manage plugin details
    permission: huskrtp.command.admin
    aliases: [hbrtp, bungeertp, brtp]
permissions:
  huskrtp.*:
    description: Lets you use all HuskBungeeRTP commands
    default: op
    children:
      - huskrtp.command.rtp
  huskrtp.command.rtp:
    description: Lets you randomly teleport
    default: op
  huskrtp.bypass_cooldown:
    description: Lets you bypass all rtp cooldown times
    default: false